config/routes.rb
Rails.application.routes.draw do

  root 'users#login' #change to login
  get 'users/login', as: :login

  get 'users/register', as: :register
  post 'users/create_session', as: :create_session

  resources :users, only: [:create]

  get 'sentences/house_latest' => 'sentences#house_latest', as: :house_latest
  resources :sentences#, only: [:index, :create]

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :user
  belongs_to :house

  validates :user, :house, :sentence_text, presence: true
  # checks whether only 1 sentence was added
  validate do |sentence|
    if sentence_text.present?
      puts "Sentence Text to validate: #{sentence.sentence_text}"
      puts "Sentence Scalpel: #{Scalpel.cut(sentence.sentence_text).length}"
      errors.add(:sentence_text, "has more than one sentence! Only one is allowed") if ((Scalpel.cut(sentence.sentence_text).length) != 1)
    end
  end

  # only allow user to post after > 2 sentences have been posted into the house sentences
  validate do |cur_sentence|
    unless (house.blank? || user.blank?) || (Sentence.where(user: user).count == 0)
      puts "House: #{house}"
      num_sentences_since = Sentence.where(house_id: house_id)
                            .where("created_at > ?", Sentence.where(user: user).order("created_at DESC").first.created_at)
                            .count
      puts "Number of sentences since last time you posted: #{num_sentences_since}"
      if num_sentences_since < 2
        errors.add(:you, "can only add a sentence after 2 other sentences have been posted!")
      end
    end

  end

  validate do |cur_sentence|
    unless cur_sentence.created_at.blank?
      if Sentence.where(house_id: house_id).where("created_at >= ?", cur_sentence.created_at).count >= 1
        errors.add(:another, "sentence has been created while you were typing, please consider changing your response :)")
      end
    end
  end

end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: [:show, :edit, :update, :destroy]
  before_action :validate_user

  def house_latest
    user_house_id = session[:user]["house_id"]
    @house_name = House.find(user_house_id).name
    @latest_sentence = Sentence.where(house_id: user_house_id).order("created_at").last.try(:sentence_text)
    @user_name = Sentence.where(house_id: user_house_id).order("created_at").last.try(:user).try(:name)
    @sentence = Sentence.new
    @counter = Sentence.where(house_id: user_house_id).count

    if @house_name == "tancho"
      @house_flag_url = "http://tembusu.nus.edu.sg/images/news_events/20120803_housereception/tancho.jpg"
      @house_color = "red"
    elsif @house_name == "gaja"
      @house_flag_url = "http://tembusu.nus.edu.sg/images/news_events/20120803_housereception/gaja.jpg"
      @house_color = "#000099"
    elsif @house_name == "ora"
      @house_flag_url = "http://tembusu.nus.edu.sg/images/news_events/20120803_housereception/ora.jpg"
      @house_color = "green"
    elsif @house_name == "ponya"
      @house_flag_url = "http://tembusu.nus.edu.sg/images/news_events/20120803_housereception/ponya.jpg"
      @house_color = "#e6b800"
    elsif @house_name == "shan"
      @house_flag_url = "http://tembusu.nus.edu.sg/images/news_events/20120803_housereception/shan.jpg"
      @house_color = "purple"
    else
      @house_flag_url = ""
      @house_color = ""
    end
  end

  # GET /sentences
  # GET /sentences.json
  def index
    @sentences = Sentence.all
  end

  # GET /sentences/1
  # GET /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @sentence = Sentence.new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences
  # POST /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)

    respond_to do |format|
      if @sentence.save
        format.html { redirect_to house_latest_path, notice: 'Sentence was successfully created.' }
        format.json { render :show, status: :created, location: @sentence }
      else
        puts @sentence.errors.full_messages
        format.html { redirect_to :house_latest, flash: {sentence_errors: @sentence.errors.full_messages, sentence_text: (@sentence.try(:sentence_text) || "")} }
        format.json { render json: @sentence.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /sentences/1
  # PATCH/PUT /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to @sentence, notice: 'Sentence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.json
  def destroy
    @sentence.destroy
    respond_to do |format|
      format.html { redirect_to sentences_url, notice: 'Sentence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def validate_user
      p session[:user]
      unless session.has_key?("user") && User.exists?(name: session[:user]["name"],
                                                      matric: session[:user]["matric"],
                                                      room_number: session[:user]["room_number"])
        redirect_to login_path, flash: {problem: "Authentication failed, could not validate matric and room number."}
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sentence_params
      mod_params = params.require(:sentence).permit(:house_id, :user_id, :sentence_text, :created_at)
      mod_params[:house_id] = session[:user]["house_id"] if mod_params[:house_id].blank?
      mod_params[:user_id] = session[:user]["id"] if mod_params[:user_id].blank?
      return mod_params
    end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/sentences/_form.html.erb
<%= form_for @sentence, :html => { :class => "form-horizontal sentence" } do |f| %>

  <% if @sentence.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sentence.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :house_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :house_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:house_id) %>
  </div>
  <div class="form-group">
    <%= f.label :sentence_text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sentence_text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sentence_text) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sentences_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sentences/edit.html.erb
<%- model_class = Sentence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sentences/house_latest.html.erb
<div class="col-xs-8 col-xs-offset-2 sentence">
  <div class="row">
   <% if flash[:sentence_errors] %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(flash[:sentence_errors].count, "error") %> prohibited this sentence from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% flash[:sentence_errors].each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="houseflag" style="background-image: url(<%= @house_flag_url %>); margin-top: 20px"></div>
      </div>
      <div class="col-xs-8">
        <h2 style="color: <%= @house_color %>; font-size: 2em"> Latest Sentence in <%= @house_name.capitalize %> (Total: <%= pluralize(@counter, "sentence" )%>)</h2>
        <h2 style="color: <%= @house_color %>; font-size: 1.6em"> By <strong><%= @user_name %> </strong></h2>
        <h3 style="font-size: 1.2em; opacity: 0.8"><%= @latest_sentence %></h3>
        <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->
      </div>
    </div>

    <div class="row">
      <%= form_for @sentence, :html => { :class => "form-horizontal sentence" } do |f| %>
        <% if @sentence.errors.any? %>
          <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title"><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence from being saved:</h3>
            </div>
            <div class="panel-body">
              <ul>
              <% @sentence.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <div class="form-group" style="margin-top: 20px">
          <%= f.label "Submit a new sentence: ", :class => 'control-label', :style =>'color:' + @house_color %>
          <%= f.text_area :sentence_text, :value => (flash[:sentence_text] || ""), :class => 'form-control' %>
          <%= f.hidden_field :created_at, :value => (DateTime.now), :class => 'form-control' %>
          <%=f.error_span(:sentence_text) %>
        </div>

        <div class="form-group">
          <center>
            <div class="">
              <%= f.submit "Submit Sentence", :class => 'btn btn-primary', :style => 'background-color:' + @house_color + '; border-color: white' %>
            </div>
          </center>
        </div>
      <% end %>
    </div>

</div>

app/views/sentences/index.html.erb
<%- model_class = Sentence -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:house_id) %></th>
      <th><%= model_class.human_attribute_name(:sentence_text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td><%= link_to sentence.id, sentence_path(sentence) %></td>
        <td><%= sentence.user_id %></td>
        <td><%= sentence.house_id %></td>
        <td><%= sentence.sentence_text %></td>
        <td><%=l sentence.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sentence_path(sentence), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sentence_path(sentence),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sentence_path,
            :class => 'btn btn-primary' %>

app/views/sentences/new.html.erb
<%- model_class = Sentence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sentences/show.html.erb
<%- model_class = Sentence -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @sentence.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:house_id) %>:</strong></dt>
  <dd><%= @sentence.house_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sentence_text) %>:</strong></dt>
  <dd><%= @sentence.sentence_text %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sentences_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sentence_path(@sentence), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sentence_path(@sentence),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>