config/routes.rb
Rails.application.routes.draw do

  root 'users#login' #change to login
  get 'users/login', as: :login

  get 'users/register', as: :register
  post 'users/create_session', as: :create_session

  resources :users, only: [:create]

  get 'sentences/house_latest' => 'sentences#house_latest', as: :house_latest
  resources :sentences#, only: [:index, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  include ApplicationHelper

  has_many :sentences
  belongs_to :house

  #have to have all these fields
  validates :name, :matric, :room_number, presence: true

  #make sure matric, room number and name are all unique. None can be shared.
  validates :name, uniqueness: true
  validates :room_number, uniqueness: true
  validates :matric, uniqueness: true

  #room number takes the form xy-abc[A-F]
  validates_format_of :room_number, :with => /\A\d{2}-\d{3}[a-fA-F]?\z/, :on => :create
  #check if the room number is in range
  validate :floor_number_in_range
  validate :matric_format_correct

  #check for house and set
  before_save do |user|
    user_floor = (room_number[0] + room_number[1]).to_i
    user_house = House.where("floor_end >= ?", user_floor).where("floor_start <= ?", user_floor).first
    user_house.present? ? user.house = user_house : errors.add(:room_number, "does not have a house!")
  end


  def self.authenticate(matric, room_number)
    #upcase everything!
    matric.try(:upcase!)
    room_number.try(:upcase!)

    User.exists?(matric: matric, room_number: room_number)
  end

  def floor_number_in_range
    unless room_number.blank?
      floor_number = room_number[0] + room_number[1]
      #people can only be from floor 3 to 21st
      errors.add(:room_number, "is not within the correct range (3 - 21)") unless (floor_number.to_i).between?(3, 21)
    else
      #errors.add(:room_number, "cannot be blank!")
    end
  end

  def matric_format_correct
    errors.add(:matric, "is not valid.") unless check_matric_number(matric)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/register
  def register
    @user = User.new
  end

  # GET /users/login
  def login

  end

  # POST /users/create_session
  def create_session
    current_params = new_session_params
    if User.authenticate(current_params[:matric], current_params[:room_number])

      current_user = User.where(matric: current_params[:matric]).where(room_number: current_params[:room_number]).first
      session[:user] = current_user

      # go to their house sentence page
      redirect_to house_latest_path

    else
      redirect_to login_path, flash: { problem: "Matric card or room number is not registered!" }
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)

    #capitalise and upcase input
    @user.name = @user.name.try(:titleize)
    @user.matric.try(:upcase!)
    @user.room_number.try(:upcase!)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created! Please log in with your matric number and room number.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :register }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    def user_params
      params.require(:user).permit(:name, :matric, :room_number)
    end

    def new_session_params
      mod_params = params.permit(:matric, :room_number)
      mod_params[:matric].try(:upcase!)
      mod_params[:room_number].try(:upcase!)
      return mod_params
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login.html.erb
<!-- LOGIN FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="tembulogo"></div>
  <h1 class="title">Pass the Paper Please</h1>
  <div class="logo">Login</div>
  <!-- Main Form -->
  <div class="login-form-1" style="width: 250px">

    <% if flash[:problem] %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"> <%= flash[:problem] %> </h3>
          </div>
        </div>
    <% end %>

    <% if flash[:notice] %>
        <div id="error_expl" class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title"> <%= flash[:notice] %> </h3>
          </div>
        </div>
    <% end %>

    <%= form_tag create_session_path, method: "post",  :html => {:class => "text-left"} do %>
    <!--<form id="login-form" class="text-left"> -->
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          <div class="form-group">
            <!--<label for="lg_username" class="sr-only">Username</label> -->
            <!--<input type="text" class="form-control" id="lg_username" name="lg_username" placeholder="username">-->
            <%= text_field_tag :matric, nil, :class => "form-control", :placeholder => "matric"%>

          </div>
          <div class="form-group">
            <!--<label for="lg_password" class="sr-only">Password</label>-->
            <!--<input type="password" class="form-control" id="lg_password" name="lg_password" placeholder="password"> -->
            <%= text_field_tag :room_number, nil, :class => "form-control", :placeholder => "room number (e.g. 08-162F)"%>
          </div>
        </div>
        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
      </div>
      <div class="etc-login-form">
      <strong>
        <p style="opacity: 1.0">new user?
          <a href="/users/register" style="padding-left: 5px">create new account</a>
        </p>
      </strong>
      </div>
    <!--</form>-->
    <% end %>
  </div>
  <!-- end:Main Form -->
</div>

app/views/users/register.html.erb
<!-- REGISTRATION FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="tembulogo"></div>
  <h1 class="title">Pass the Paper Please</h1>
  <div class="logo">Register</div>

  <!-- Main Form -->

  <div class="login-form-1">
    <!-- Errors -->
  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Unable to register due to <%= pluralize(@user.errors.count, "error") %>:</h3>
      </div>
      <div class="panel-body" style="background-color: orange !important">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    <!--<form id="register-form" class="text-left"> -->
    <%= form_for @user, :html => {:class => "text-left"} do |f|%>
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">

          <div class="form-group">
            <!--<label for="reg_username" class="sr-only">Matric Card Number</label> -->
            <!--<input type="text" class="form-control" id="reg_username" name="reg_username" placeholder="matric card number">-->
            <%= f.text_field :matric, :class => "form-control", :placeholder => "matric"%>
          </div>
          <div class="form-group">
            <!--<label for="reg_password" class="sr-only">Password</label>-->
            <!--<input type="password" class="form-control" id="reg_password" name="reg_password" placeholder="room number (e.g. 08-162F)">-->
            <%= f.text_field :room_number, :class => "form-control", :placeholder => "room number (e.g. 08-162F)"%>
          </div>


          <div class="form-group">
            <!--<label for="reg_fullname" class="sr-only">Full Name</label>-->
            <!--<input type="text" class="form-control" id="reg_fullname" name="reg_fullname" placeholder="full name"> -->
            <%= f.text_field :name, :class => "form-control", :placeholder => "name"%>
          </div>
        </div>
        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
      </div>
      <div class="etc-login-form">
      <strong>
        <p style="opacity: 1.0">already have an account?
          <a href="/users/login" style="padding-left: 5px">login here</a>
        </p>
        </strong>
      </div>
    <% end %>
    <!--</form>-->
  </div>
  <!-- end:Main Form -->
</div>